# -*- coding: utf-8 -*-
"""OpenAI_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMTbcN1NLMHP5q3dNJUua5pDt1SLOQOo
"""

pip install --upgrade openai

import os
import pandas as pd

# read in all data then split for processing if required
all_input = pd.read_csv('/content/100_words_2_more_random_big4.csv')
all_input.shape

df1 = all_input.iloc[:599]
df2 = all_input.iloc[599:1200]
df3 = all_input.iloc[1200:1799]
df4 = all_input.iloc[1799:2400]
df5 = all_input.iloc[2400:2999]
df6 = all_input.iloc[2999:3599]
df7 = all_input.iloc[3599:]

df1

from openai import OpenAI

client = OpenAI(
    api_key="",
)

def get_chat_completion(prompt, text, model="gpt-3.5-turbo-0125"):

   prompt = prompt + text + "```"
   # Creating a message as required by the API
   messages = [{"role": "user", "content": prompt}]

   # Calling the ChatCompletion API
   response = client.chat.completions.create(
       model=model,
       messages=messages,
       temperature=0.7,
   )

   # Returning the extracted response
   return response.choices[0].message.content

def loop_responses():
  # update to required data frame
  input = df1#all_input
  texts = input['final'].tolist()
  prompt = "You will take the role of an author of crime novels. A text excerpt will be provided, you have to review it for number of space characters and key details. Create a new text excerpt which contains the same key details but appears structurally different to the original. The new text must have approximately the same number of spaces as the original. Only return the new text passage. Do not include place holders, line breaks or any other text except the new passage. Text excerpt:  ```"
  results = []
  for text in texts:
    response = get_chat_completion(prompt, text)
    results.append(response)
  print(results)
  df = pd.DataFrame(results)
  # change csv name as required
  df.to_csv('results_from_big4_agatha.csv', index=False)

loop_responses()